### ISSUE TITLE
Wrong location

### ISSUE THREAD

**Issue by ramonsergas** [cetrespeo/ESP32-E-Paper-Weather#1]
Although I write my location into the sketch, OpenWeatherMap takes the location of a village nearby.

Is it possible that OpenWeatherMap is using my IP to return wrong values?

**Comment by cetrespeo** [comment]
Hola Ramón,

Weather info is downloaded from darsky.net, not OpenWeatherMap. You can use OpenWeatherMap but then you need to update the variable names.

Regarding GPS position, I recommend you use maps.google.com and then obtain the GPS position in decimal degrees from google maps' URL.

For example, if you search "Beire" in google maps you will get https://www.google.com/maps/place/31393+Beire,+Navarra/@42.4559815,-1.6218852,17z

GPS position is 42.4559815,-1.6218852.

If you find that inaccurate, move and zoom as needed.

**Comment by ramonsergas** [comment]
Well... It doesn't work.
I put into the sketch my location, Soria (41.7646437,-2.461848) and always takes me to Golmayo (41.7654912,-2.5226205)
Not much to worry about, but enough to think about it.

**Comment by cetrespeo** [comment]
You mean, the text on the down right side of the screen?

That name is not taken from the GPS position for weather. It is indeed taken from the IP position given by the provider, that's why you don't have the same name. Now I understand your issue. 

The problem is based in the information given by the darsky.net. They don't give the name of the targeted town, so I take it from https://ipinfo.io/json . It is quite usual that the IP exit city name is other.

Said so, there is a solution. In order to change that location name in the bottom right side, you can edit "Custom Text" in your Firebase params and problem solved.

**Comment by ramonsergas** [comment]
Right! That text

**Comment by cetrespeo** [comment]
Did you setup a Firebase account ?

**Comment by ramonsergas** [comment]
No. I deleted both settings. I let it like “”

**Comment by cetrespeo** [comment]
Good to know!  I'm glad you like it!

Enjoy! :-)

**Comment by cetrespeo** [comment]
Graph values explanation added to the end of the readme file.
