### ISSUE TITLE
Code does not Compile

### ISSUE THREAD

**Issue by Bjoern2708** [cetrespeo/ESP32-E-Paper-Weather#7]
Hello,

I really liked the idea of a weather Station on an E-Paper display, so I have just bought the required hardware for the Project. Unfortunatly I could not get the code too compile. The only difference is, that I am using the White/Black/Yellow version of the E-Paper, but that shoult not matter. Could you please help me to find the fault? Here ist the Hardware I am currently using:

Waveshare E-Paper Display:
https://www.reichelt.de/entwicklerboards-display-epaper-4-2-schwarz-weiss-gelb-debo-epa-4-2-ye-p253963.html?PROVID=2788&gclid=EAIaIQobChMI-OzyjuaVgAMVDOF3Ch3HPw_nEAQYAiABEgI36fD_BwE

Wemos Lolin 32:
https://www.ebay.de/itm/353070851524?chn=ps&_trkparms=ispr%3D1&amdata=enc%3A11qX78YJpSpaPwDvuxRzLwA33&norover=1&mkevt=1&mkrid=707-134425-41852-0&mkcid=2&mkscid=101&itemid=353070851524&targetid=1716911582639&device=c&mktype=pla&googleloc=9041696&poi=&campaignid=17943303986&mkgroupid=140642150118&rlsatarget=pla-1716911582639&abcId=9301060&merchantid=494568102&gclid=EAIaIQobChMI_NatnuaVgAMVkIKDBx15dAjTEAQYAiABEgLg4_D_BwE

Or is the new Arduino IDE the problem? Iam currently on the latest version (V2.1.1).  I only have modified the "config" file, the main code itself is untouched. I also tried the code on a completly fresh installation of the Arduino IDE but unfortunatly that didn´t worked. I also attached a screenshot of the error.

![image](https://github.com/cetrespeo/ESP32-E-Paper-Weather/assets/139245704/ab18548f-a6df-45c5-81aa-67ed9df4e1ad)

Björn

**Comment by cetrespeo** [comment]
Hi Björn,

My experience with Arduino libraries ecosystem is quite erratic, but all I have learned is that you need to stick to the allowed versions in order to be able to compile them all together. 

The problem of this application is that we are in the limit of the RAM, and FLASH, so we cannot use libraries that take too much space. That is why I recommend not to use libraries higher that those posted in the Readme. Otherwise, you will have incompatibility issues and will not fit on flash. Important not to use ArduinoJson higher than 5.13 and FirebaseESP32 higher than 3.8.8. Also avoid indirect install of Adafruit BusIO higher then 1.11.0, and use ESP32 1.0.4 library (has it has lower RAM usage).

Arduino 2.xx is also a problem as it takes higher resources when compiled, so I always stick to Anduino 1.8.19.

With those versions, I can compile all fitting (to the limit) on Flash and Ram.

I hope to have helped you a little :-)

Thanks,

Unai

**Comment by doanerock** [comment]
using visual studio code with platformio plugin is handy because you can specify arduino and library versions using the platformio.ini file.

**Comment by Bjoern2708** [comment]
Thanks a lot for the reply! I have tryed it again with a completly fresh installation of the Arduino IDE 1.8.19 (From the Windows Store). The ammount of issues went down, but is not compeltly gone yet. I get a compilation errror, that there were multiple librarys found for "SD.h" and "WiFi.h". I also had to install an additional library for "GxEPD.h" (V. 3.1.3). But I think that does not effect the result. I also uploaded some screenshots of the installed libarary / board manager. 

Also thanks @doanerock for the reply but I would like to stay at the arduino IDE, because I am not really familiar with visual studio. Thanks anyway. 

![Compilation Error](https://github.com/cetrespeo/ESP32-E-Paper-Weather/assets/139245704/7b1453b5-9170-454e-aab3-4997e3cb84de)

![ESP32 Boardmanager](https://github.com/cetrespeo/ESP32-E-Paper-Weather/assets/139245704/a1a914af-71ab-44ba-9cb1-4a719cb88706)

![ArduinoJson](https://github.com/cetrespeo/ESP32-E-Paper-Weather/assets/139245704/78a96ac4-7b3a-4479-b706-e58fd950ea66)

![Firebase ESP32 Client](https://github.com/cetrespeo/ESP32-E-Paper-Weather/assets/139245704/db4ff2fe-46f2-4216-8a76-a1818fdd081a)

![Adafruit BusIO](https://github.com/cetrespeo/ESP32-E-Paper-Weather/assets/139245704/c60a0dcf-f20c-4e55-821d-91fbc683ec1f)

![GxEPD](https://github.com/cetrespeo/ESP32-E-Paper-Weather/assets/139245704/7c6a38e7-8e7f-450b-b581-45c287bbcf7f)

Björn

**Comment by cetrespeo** [comment]
Hi Björn,

Just compiled again, and it runs for me. As there are too many libraries we are at the limit of the ESP32 (In fact, you will need to adapt the boards.txt to have the OTA option).

Your versions are correct, but please check if you are using Adafruit Gfx 1.11.3, and you have U2g8_for_Adafruit_GFX 1.8.0

I leave you a libraries.zip file in the code folder with the libraries i am using.

I hope to have helped you with this nightmare :-). It is been years since I don't touch this code, but now I am thrilled with new uses...

Thanks for your interest.

Unai

**Comment by Bjoern2708** [comment]
Hi Unai,

Sorry for replying so late. This was indeed the problem. Now it compiled and uploded fine. The "libary.zip" was a huge help! I just have one last issue. When I edit the "sWeatherLOC" in the "config.h" file, and upload it again, it does not update the location at the weather station. It is showing some informations on the display, but for the wrong location. I took the GPS location from the URL at google maps, so this should be fine. For testing, I edited the name of the "WeekDayNames" and they are actually changing when I uplod the code again. So the upload process isn´t the problem, but for some reasons the config.h file does not get overwritten on the esp32, when it is uploaded again. But beside of that the weather station looks awesom. Really great work!

![E-Paper_weather_station](https://github.com/cetrespeo/ESP32-E-Paper-Weather/assets/139245704/63b1016a-da82-4e3f-b67c-18eb12789d69)

Björn

**Comment by cetrespeo** [comment]
Glad you like it Björn.

Please check your WeatherLocation as I guess you are "pointing to water" :-). In case you want, you can send me a message and I will try to help you defining the sWeatherLoc. 

Please remember that order is Latitude and Longitude. You should be able to see your town in google maps, just entering the string. P.e., Amsterdam will be "52.37,4.92"

Kind regards,

Unai

**Comment by cetrespeo** [comment]
Compilation issue solved. Closed
