### ISSUE TITLE
ESP32 LOIN32 - no display on the e-Paper but  error messages 

### ISSUE THREAD

**Issue by xsnoopy1958** [cetrespeo/ESP32-E-Paper-Weather#8]
Hello,
I have compiled the sketch without error messages and uploaded it to ESP32.
But there is nothing on the display.
The following error messages can be seen in the serial monitor (see attachment).

[error messages.txt](https://github.com/cetrespeo/ESP32-E-Paper-Weather/files/12327136/error.messages.txt)

Can you help.
I am using a LOIN32 (not a LOLIN32) with Waveshare 4.2 inch b/w/r display.
It would be great, if you could me an advice.

**Comment by cetrespeo** [comment]
Hi,

At first sight you have problems with Wifi connection, and there is something in the setup wrong.

In the debug I can see "Weather/0'0,0'0". You didn't setup the config file.

Please define the config.h file as required. sWeatherLOC cannot be "x.xx,x.xx" because you are pointing nowhere.

Please read the instructions

**Comment by xsnoopy1958** [comment]
Hello,
thank you for your quickly answer.

please find attached the config:

[config.h.zip](https://github.com/cetrespeo/ESP32-E-Paper-Weather/files/12327470/config.h.zip)

**Comment by xsnoopy1958** [comment]
Hi,
thank you for your quickly answer.
Please find attached the config.h-File:

[config.zip](https://github.com/cetrespeo/ESP32-E-Paper-Weather/files/12327490/config.zip)

**Comment by cetrespeo** [comment]
Hi,

Please recompile with the config.h of the previous post and send debug in case it gives more errors.  That config should now work in case your wifi doesn't fail. 

Also check wiring of display

**Comment by xsnoopy1958** [comment]
Hi,
my display is a waveshare 4.2 inch 3 color,  V2.

 Can the v2 version be the problem?
Do I have to use a different graphics library for V2? GxEPD2

What would I have to change in the code?
I am a beginner and do not know anything.

Regards
Bernd

Sent from MailDroid

-----Original Message-----

**Comment by cetrespeo** [comment]
ha, ha.... I am also a beginner Bernd. As you can see in my spaghetti-code, I am not a professional :-) . This is was one of my hobbies a few years ago. Many hours of trial and error that lead to a somehow working gadget.

I couldn't fit GxEPD2 on flash. Passing to GxEPD2 requires new functions and removing things to make room for the new library. 
But in a short research, I saw in (https://www.waveshare.com/wiki/4.2inch_e-Paper_Module_(B)_Manual#Overview) that "V2 hardware and interfaces are compatible with V1". So I guess that will not affect in case GxEPD allows it. Did you check yours is GDEW042Z15 ?. 

One good test is to check a GxEPD demo in your display and discard other wiring problems. In case you can see a demo image in the display with one of the GxEPD demos using GDEW042Z15, then you know the problem is in the WeatherApp setup.

In case you need more help, please share debug so I can check where did you get stuck.

**Comment by xsnoopy1958** [comment]
Hi,
thank you for quickly reply.
I will try this.

Bernd


Sent from MailDroid

-----Original Message-----

**Comment by xsnoopy1958** [comment]
Hello,
The wiring is fine and working. I have checked it with another project.

Unfortunately, the Waveshare V2 does not work with the GxEPD, but only with the new GxEPD2. Here the LOLIN32 will surely be too small.
Would the new D32 help here?

 I have tried to get a Waveshare 4.2 b/ w/red with version V1.
Unfortunately so far noChance.
Do you have any idea?

I would love to build this weather station.

Can you help me further?

Regards

Bernd Schröder

Sent from MailDroid

-----Original Message-----

**Comment by cetrespeo** [comment]
Hi Bernd,

D32 will not help a lot as Heap memory is not considered in this version. Not an easy solution.

Changing to GxEPD2 will require removing other things. I could make a paralell project with less things and then add GxEPD2, but this is a large project for me now as I have little spare time now.

Maybe in the future, when winter sends me home. My recommendation is to buy a v1 version board with the supported board, or try it on your own (it is a good hobby but not for summertime :-) ).

Regards,

Unai

**Comment by Bjoern2708** [comment]
Hi Bernd,

I have used the V2 Version of the Display "White/Black/Yellow" and it worked perfectly (Combined with a Wemos LOLIN32). I did not changed any library in the code, so it should theorytically work. You could also try the example code from waveshare for your diplay, then you will see if your wiring is correct and if the display showes an image. Have you used the Arduino IDE 1.8.XX? I got a lot of errors with the 2.XX IDE.

https://www.waveshare.com/wiki/4.2inch_e-Paper_Module_(B)

Regards,

Björn
